// Generated by dts-bundle v0.7.3

declare module 'myModule' {
    /**
        * Form base
        */
    export class FormBase {
            appName: string;
            context: Xrm.Events.EventContext;
            /**
                * Creates an instance of form base.
                * @param context
                */
            constructor(context: Xrm.Events.EventContext);
            initContextViaDecorator(context: Xrm.Events.EventContext): void;
            /**
                * Gets form context
                */
            get formContext(): Xrm.FormContext;
    }
    /**
        * Inits crm form
        * @param context
        * @returns
        */
    export function initCrmForm(context: Xrm.Events.EventContext): any;
    export function initForm(target: FormBase, propertyKey: string, descriptor: any): any;
}

